language: cpp
dist: bionic

addons:
  apt:
    packages: &default_pkgs
      - libglib2.0-dev
      - python3-pip
      - python3-setuptools
      # - libstdc++6-4.9-dbg
      - ninja-build

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERC=gcc-7
        - COMPILERCXX=g++-7
        - LLVM_CONFIG=llvm-config-9
      addons:
        apt:
          packages:
            - *default_pkgs
            - llvm-9-dev
            - gcc-7
            - g++-7
    # Note: Clang 9 fails to link against LLVM for an unknown reason:
    #   undefined reference to `llvm::cfg::Update<llvm::BasicBlock*>::dump() const'
    # Reconsider adding Clang to CI once rebasing to LLVM 10
    # - compiler: clang
    #   env:
    #     - COMPILERC=clang-9
    #     - COMPILERCXX=clang++-9
    #     - LLVM_CONFIG=llvm-config-9
    #   addons:
    #     apt:
    #       packages:
    #         - *default_pkgs
    #         - llvm-9-dev
    #         - clang-9

install:
  # The meson included in the Xenial repositories is too old (0.29).
  - pip3 install meson
  # Hack to work around different versions of LLVM being installed and meson
  # always choosing the newest one, regardless of our specifications.
  - ln -s /usr/bin/$LLVM_CONFIG $HOME/.local/bin/llvm-config
  - export CC=$COMPILERC
  - export CXX=$COMPILERCXX

script:
  - mkdir build
  - meson build
  - ninja -v -C build
  - meson test -v -C build
